version: "3"

volumes:
  cleaning_scheduler_local_postgres_data: {}
  cleaning_scheduler_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cleaning_scheduler_local_django
    container_name: cleaning_scheduler_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cleaning_scheduler_production_postgres
    container_name: cleaning_scheduler_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - cleaning_scheduler_local_postgres_data:/var/lib/postgresql/data
      - cleaning_scheduler_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: cleaning_scheduler_local_docs
    container_name: cleaning_scheduler_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cleaning_scheduler:/app/cleaning_scheduler:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailpit:
    image: axllent/mailpit:latest
    container_name: cleaning_scheduler_local_mailpit
    ports:
      - "8025:8025"
