# Generated by Django 4.2.9 on 2024-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning_scheduler", "0002_booking_cleaningschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="cleaningschedule",
            name="cleaning_date",
            field=models.DateTimeField(),
        ),
    ]
