# Generated by Django 4.2.9 on 2024-01-30 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning_scheduler", "0003_alter_booking_check_in_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cleaningschedule",
            name="apartment",
        ),
    ]
