# Generated by Django 4.2.9 on 2024-01-31 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cleaning_scheduler", "0005_remove_apartment_cleaning_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apartment",
            unique_together={("name", "owner")},
        ),
    ]
