# Generated by Django 4.2.9 on 2024-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cleaning_scheduler", "0006_alter_apartment_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaningschedule",
            name="window_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cleaningschedule",
            name="window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
